debug: true
logging.level.root: INFO


management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include=*
    health:
      show-details: always
      show-componets : always
      defaults:
        enabled: true
